// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Shared.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Shared.Data
{
    public partial interface IInmobiliariaDbContextProcedures
    {
        Task<List<SP_GET_AERIResult>> SP_GET_AERIAsync(int? IDProperty, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GET_AERI_AREASResult>> SP_GET_AERI_AREASAsync(int? IDProperty, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GET_AERI_DELIVERABLESResult>> SP_GET_AERI_DELIVERABLESAsync(int? IDProperty, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GET_AERI_HEADERResult>> SP_GET_AERI_HEADERAsync(int? IDProperty, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
