// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SharedLibrary.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SharedLibrary.Data
{
    public partial class InmobiliariaDbContext
    {
        private IInmobiliariaDbContextProcedures _procedures;

        public virtual IInmobiliariaDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new InmobiliariaDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IInmobiliariaDbContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SP_GET_AERI_AREASResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SP_GET_AERI_DELIVERABLESResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SP_GET_AERI_HEADERResult>().HasNoKey().ToView(null);
        }
    }

    public partial class InmobiliariaDbContextProcedures : IInmobiliariaDbContextProcedures
    {
        private readonly InmobiliariaDbContext _context;

        public InmobiliariaDbContextProcedures(InmobiliariaDbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_GET_AERI_AREASResult>> SP_GET_AERI_AREASAsync(int? IDProperty, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDProperty",
                    Value = IDProperty ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_GET_AERI_AREASResult>("EXEC @returnValue = [dbo].[SP_GET_AERI_AREAS] @IDProperty", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_GET_AERI_DELIVERABLESResult>> SP_GET_AERI_DELIVERABLESAsync(int? IDProperty, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDProperty",
                    Value = IDProperty ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_GET_AERI_DELIVERABLESResult>("EXEC @returnValue = [dbo].[SP_GET_AERI_DELIVERABLES] @IDProperty", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_GET_AERI_HEADERResult>> SP_GET_AERI_HEADERAsync(int? IDProperty, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDProperty",
                    Value = IDProperty ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_GET_AERI_HEADERResult>("EXEC @returnValue = [dbo].[SP_GET_AERI_HEADER] @IDProperty", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
