// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SharedLibrary.Models
{
    public partial class Activity
    {
        public Activity()
        {
            Elements = new HashSet<Element>();
        }

        [Key]
        [Column("ID_Activity")]
        public int IdActivity { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string ActivityName { get; set; }

        [InverseProperty("IdActivityNavigation")]
        public virtual ICollection<Element> Elements { get; set; }
    }
}