// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Keyless]
    [Table("ActionCatalog")]
    public partial class ActionCatalog
    {
        [Required]
        [Column("ID_ActionCatalog")]
        [StringLength(2)]
        [Unicode(false)]
        public string IdActionCatalog { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string TypeAction { get; set; }
        [Column("ID_Module")]
        public int IdModule { get; set; }

        [ForeignKey("IdModule")]
        public virtual Module IdModuleNavigation { get; set; }
    }
}