// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SharedLibrary.Models
{
    public partial class Area
    {
        public Area()
        {
            ProgressReports = new HashSet<ProgressReport>();
            IdActivities = new HashSet<Activity>();
        }

        [Key]
        [Column("ID_Area")]
        public int IdArea { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string AreaName { get; set; }

        [InverseProperty("IdAreaNavigation")]
        public virtual ICollection<ProgressReport> ProgressReports { get; set; }

        [ForeignKey("IdArea")]
        [InverseProperty("IdAreas")]
        public virtual ICollection<Activity> IdActivities { get; set; }
    }
}