// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SharedLibrary.Models
{
    public partial class AreaService
    {
        [Key]
        [Column("ID_Area")]
        public int IdArea { get; set; }
        [Key]
        [Column("ID_Service")]
        public int IdService { get; set; }
        [Key]
        [Column("ID_Property")]
        public int IdProperty { get; set; }

        [ForeignKey("IdArea")]
        [InverseProperty("AreaServices")]
        public virtual Area IdAreaNavigation { get; set; }
        [ForeignKey("IdProperty")]
        [InverseProperty("AreaServices")]
        public virtual Property IdPropertyNavigation { get; set; }
        [ForeignKey("IdService")]
        [InverseProperty("AreaServices")]
        public virtual Service IdServiceNavigation { get; set; }
    }
}