// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SharedLibrary.Models
{
    public partial class Area
    {
        public Area()
        {
            Inventories = new HashSet<Inventory>();
        }

        [Key]
        [Column("ID_Area")]
        public int IdArea { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string AreaName { get; set; }

        [InverseProperty("IdAreaNavigation")]
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}