// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Models
{
    public partial class Blob
    {
        public Blob()
        {
            BlobsInventories = new HashSet<BlobsInventory>();
        }

        public int IdBlobs { get; set; }
        public string ContentType { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public string BlodName { get; set; }
        public string BlodTypeId { get; set; }
        public string ContainerName { get; set; }
        public bool IsPrivate { get; set; }
        public string Uri { get; set; }
        public string BlobSize { get; set; }

        public virtual ICollection<BlobsInventory> BlobsInventories { get; set; }
    }
}