// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SharedLibrary.Models
{
    public partial class Blob
    {
        [Key]
        [Column("ID_Blobs")]
        public int IdBlobs { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string ContentType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateModified { get; set; }
        [StringLength(60)]
        [Unicode(false)]
        public string BlodName { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string BlodTypeId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string ContainerName { get; set; }
        public bool? IsPrivate { get; set; }
        [Required]
        [Unicode(false)]
        public string Uri { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string BlobSize { get; set; }
    }
}