// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Models
{
    public partial class BlobsInventory
    {
        public int IdBlobsInventory { get; set; }
        public int IdProperty { get; set; }
        public int IdInventory { get; set; }
        public int IdBlobs { get; set; }

        public virtual Blob IdBlobsNavigation { get; set; }
        public virtual Inventory IdInventoryNavigation { get; set; }
        public virtual Property IdPropertyNavigation { get; set; }
    }
}