// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Models
{
    public partial class Description
    {
        public Description()
        {
            Inventories = new HashSet<Inventory>();
        }

        public int IdDescription { get; set; }
        public string DescriptionName { get; set; }
        public int IdFeature { get; set; }

        public virtual Feature IdFeatureNavigation { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}