// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SharedLibrary.Models
{
    public partial class Element
    {
        public Element()
        {
            ProgressReports = new HashSet<ProgressReport>();
            SubElements = new HashSet<SubElement>();
        }

        [Key]
        [Column("ID_Element")]
        public int IdElement { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string ElementName { get; set; }
        [Column("ID_Activity")]
        public int IdActivity { get; set; }

        [ForeignKey("IdActivity")]
        [InverseProperty("Elements")]
        public virtual Activity IdActivityNavigation { get; set; }
        [InverseProperty("IdElementNavigation")]
        public virtual ICollection<ProgressReport> ProgressReports { get; set; }
        [InverseProperty("IdElementNavigation")]
        public virtual ICollection<SubElement> SubElements { get; set; }
    }
}