// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Models
{
    public partial class Feature
    {
        public Feature()
        {
            Descriptions = new HashSet<Description>();
        }

        public int IdFeature { get; set; }
        public string FeatureName { get; set; }
        public int IdService { get; set; }

        public virtual Service IdServiceNavigation { get; set; }
        public virtual ICollection<Description> Descriptions { get; set; }
    }
}