// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SharedLibrary.Models
{
    public partial class Feature
    {
        public Feature()
        {
            Descriptions = new HashSet<Description>();
        }

        [Key]
        [Column("ID_Feature")]
        public int IdFeature { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string FeatureName { get; set; }
        [Column("ID_Service")]
        public int IdService { get; set; }

        [ForeignKey("IdService")]
        [InverseProperty("Features")]
        public virtual Service IdServiceNavigation { get; set; }
        [InverseProperty("IdFeatureNavigation")]
        public virtual ICollection<Description> Descriptions { get; set; }
    }
}