// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Models
{
    public partial class Inventory
    {
        public Inventory()
        {
            BlobsInventories = new HashSet<BlobsInventory>();
        }

        public int IdInventory { get; set; }
        public int IdProperty { get; set; }
        public int IdArea { get; set; }
        public int IdDescription { get; set; }
        public string Note { get; set; }
        public string Observation { get; set; }

        public virtual Area IdAreaNavigation { get; set; }
        public virtual Description IdDescriptionNavigation { get; set; }
        public virtual Property IdPropertyNavigation { get; set; }
        public virtual ICollection<BlobsInventory> BlobsInventories { get; set; }
    }
}