// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Table("LaneCatalog")]
    public partial class LaneCatalog
    {
        public LaneCatalog()
        {
            FinalPosts = new HashSet<FinalPost>();
            Tariffs = new HashSet<Tariff>();
            Transactions = new HashSet<Transaction>();
        }

        [Key]
        [Column("ID_Catalog")]
        public int IdCatalog { get; set; }
        [Column("ID_Strech")]
        [StringLength(10)]
        public string IdStrech { get; set; }
        [Column("ID_Square")]
        [StringLength(10)]
        public string IdSquare { get; set; }
        [Column("ID_Side")]
        [StringLength(10)]
        public string IdSide { get; set; }
        [Column("ID_Lane")]
        [StringLength(10)]
        public string IdLane { get; set; }
        [Required]
        [StringLength(150)]
        public string Name { get; set; }
        [StringLength(150)]
        public string Description { get; set; }
        [Column("ID_TypeVoie")]
        [StringLength(5)]
        public string IdTypeVoie { get; set; }

        [InverseProperty("IdCatalogNavigation")]
        public virtual ICollection<FinalPost> FinalPosts { get; set; }
        [InverseProperty("IdCatalogNavigation")]
        public virtual ICollection<Tariff> Tariffs { get; set; }
        [InverseProperty("IdCatalogNavigation")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}