// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Models
{
    public partial class Lessor
    {
        public Lessor()
        {
            Properties = new HashSet<Property>();
        }

        public int IdLessor { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Rfc { get; set; }
        public string Street { get; set; }
        public string Colony { get; set; }
        public string Delegation { get; set; }
        [Required]
        [Column("CP")]
        [StringLength(10)]
        public string Cp { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }

        public virtual ICollection<Property> Properties { get; set; }
    }
}