// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Table("LogTagList")]
    public partial class LogTagList
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("TAG")]
        [StringLength(50)]
        public string Tag { get; set; }
        [Column("ACTIVE")]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime UpdatedDate { get; set; }
        [Column("ID_User")]
        [StringLength(450)]
        public string IdUser { get; set; }
        [Required]
        [StringLength(8)]
        public string VehiclePlate { get; set; }
        [Required]
        [StringLength(10)]
        public string EconomicNumber { get; set; }
        [Column("ID_VIATags")]
        public int? IdViatags { get; set; }

        [ForeignKey("IdUser")]
        [InverseProperty("LogTagLists")]
        public virtual AspNetUser IdUserNavigation { get; set; }
    }
}