// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Table("LogUserActivity")]
    public partial class LogUserActivity
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ID_ModifiedUser")]
        [StringLength(450)]
        public string IdModifiedUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime UpdatedDate { get; set; }
        [Required]
        [Column("ID_UpdatedUser")]
        [StringLength(450)]
        public string IdUpdatedUser { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string TypeAction { get; set; }
        [StringLength(450)]
        public string AspNetRolesIdOld { get; set; }
        [StringLength(450)]
        public string AspNetRolesIdNew { get; set; }
        [StringLength(60)]
        public string OldName { get; set; }
        [StringLength(60)]
        public string NewName { get; set; }
        [StringLength(60)]
        public string OldLastName { get; set; }
        [StringLength(60)]
        public string NewLastName { get; set; }
        public string OldPass { get; set; }
        public string NewePass { get; set; }
        public bool Active { get; set; }
    }
}