// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Models
{
    public partial class Module
    {
        public int Id { get; set; }
        public string NameModule { get; set; }
        public string Image { get; set; }
        public string Route { get; set; }
    }
}