// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SharedLibrary.Models
{
    public partial class ProgressReport
    {
        public ProgressReport()
        {
            ProgressLogs = new HashSet<ProgressLog>();
        }

        [Key]
        [Column("ID_ProgressReport")]
        public int IdProgressReport { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column("ID_Building")]
        public int IdBuilding { get; set; }
        [Column("ID_Apartment")]
        public int IdApartment { get; set; }
        [Column("ID_Area")]
        public int IdArea { get; set; }
        [Column("ID_Element")]
        public int IdElement { get; set; }
        [Column("ID_SubElement")]
        public int? IdSubElement { get; set; }
        [StringLength(5)]
        [Unicode(false)]
        public string TotalPieces { get; set; }
        [Column("ID_Supervisor")]
        [StringLength(450)]
        public string IdSupervisor { get; set; }

        [ForeignKey("IdApartment")]
        [InverseProperty("ProgressReports")]
        public virtual Apartment IdApartmentNavigation { get; set; }
        [ForeignKey("IdArea")]
        [InverseProperty("ProgressReports")]
        public virtual Area IdAreaNavigation { get; set; }
        [ForeignKey("IdBuilding")]
        [InverseProperty("ProgressReports")]
        public virtual Building IdBuildingNavigation { get; set; }
        [ForeignKey("IdElement")]
        [InverseProperty("ProgressReports")]
        public virtual Element IdElementNavigation { get; set; }
        [ForeignKey("IdSubElement")]
        [InverseProperty("ProgressReports")]
        public virtual SubElement IdSubElementNavigation { get; set; }
        [ForeignKey("IdSupervisor")]
        [InverseProperty("ProgressReports")]
        public virtual AspNetUser IdSupervisorNavigation { get; set; }
        [InverseProperty("IdProgressReportNavigation")]
        public virtual ICollection<ProgressLog> ProgressLogs { get; set; }
    }
}