// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Models
{
    public partial class ReceptionCertificate
    {
        public int IdReceptionCertificate { get; set; }
        public int IdProperty { get; set; }
        public int IdTenant { get; set; }
        public DateTime CreationDate { get; set; }
        public string ContractNumber { get; set; }
        public string Observation { get; set; }
        public string ApprovarPathLessor { get; set; }
        public string ApprovalPathTenant { get; set; }
        public string Stamp { get; set; }
        public string IdAgent { get; set; }
        public int IdTypeRecord { get; set; }

        public virtual AspNetUser IdAgentNavigation { get; set; }
        public virtual Property IdPropertyNavigation { get; set; }
        public virtual Tenant IdTenantNavigation { get; set; }
    }
}