// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Table("SackStatement")]
    public partial class SackStatement
    {
        [Key]
        [Column("ID_Sac")]
        public int IdSac { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateSac { get; set; }
        public int? Sac { get; set; }
        [Column("Poste_RCT_Monnaie1")]
        public int PosteRctMonnaie1 { get; set; }
        [Column("Red_RCT_Devise")]
        public int RedRctDevise { get; set; }
        [Column("Red_RCT_monnaie1")]
        public int? RedRctMonnaie1 { get; set; }
        public int? TraficTotal { get; set; }
        [StringLength(50)]
        public string UserCommentary { get; set; }
        [StringLength(250)]
        public string Commentary { get; set; }
        [Column("ID_Catalog")]
        public int IdCatalog { get; set; }
        [Column("ID_User")]
        public int IdUser { get; set; }
        [Column("VERSION_DEVISE")]
        public int? VersionDevise { get; set; }
    }
}