// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SharedLibrary.Models
{
    public partial class Service
    {
        public Service()
        {
            AreaServices = new HashSet<AreaService>();
            Features = new HashSet<Feature>();
        }

        [Key]
        [Column("ID_Service")]
        public int IdService { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string ServiceName { get; set; }

        [InverseProperty("IdServiceNavigation")]
        public virtual ICollection<AreaService> AreaServices { get; set; }
        [InverseProperty("IdServiceNavigation")]
        public virtual ICollection<Feature> Features { get; set; }
    }
}