// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Models
{
    public partial class Service
    {
        public Service()
        {
            Features = new HashSet<Feature>();
        }

        public int IdService { get; set; }
        public string ServiceName { get; set; }

        public virtual ICollection<Feature> Features { get; set; }
    }
}