// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SharedLibrary.Models
{
    public partial class SP_GET_AERI_AREASResult
    {
        public long? ID_AREA { get; set; }
        public long? ID2 { get; set; }
        public string Area { get; set; }
        public string ELEMENTO { get; set; }
        [Column("Cantidad/Descripcion")]
        public string CantidadDescripcion { get; set; }
        public string Observaciones { get; set; }
        public string Uri { get; set; }
    }
}
