// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SharedLibrary.Models
{
    public partial class SP_GET_AERI_DELIVERABLESResult
    {
        public long? ID_ENTREGABLE { get; set; }
        public long? ID2 { get; set; }
        public string Entregable { get; set; }
        [Column("Area/Servicio")]
        public string AreaServicio { get; set; }
        public string Cantidad { get; set; }
        public string Observaciones { get; set; }
        public string Uri { get; set; }
    }
}
