// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Shared.Models
{
    public partial class SP_GET_AERIImagesResult
    {
        public string Area { get; set; }
        public int ID_Property { get; set; }
        public int ID_Blobs { get; set; }
        public string Uri { get; set; }
    }
}
