// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SharedLibrary.Models
{
    public partial class Status
    {
        public Status()
        {
            ProgressLogs = new HashSet<ProgressLog>();
        }

        [Key]
        [Column("ID_Status")]
        public int IdStatus { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string StatusName { get; set; }

        [InverseProperty("IdStatusNavigation")]
        public virtual ICollection<ProgressLog> ProgressLogs { get; set; }
    }
}