// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SharedLibrary.Models
{
    public partial class SubElement
    {
        [Key]
        [Column("ID_SubElement")]
        public int IdSubElement { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string SubElementName { get; set; }
        [Column("ID_Element")]
        public int IdElement { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Type { get; set; }

        [ForeignKey("IdElement")]
        [InverseProperty("SubElements")]
        public virtual Element IdElementNavigation { get; set; }
    }
}