// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Table("TagList")]
    public partial class TagList
    {
        [Key]
        [StringLength(50)]
        public string Tag { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertionDate { get; set; }
        public bool Active { get; set; }
        [Column("ID_User")]
        [StringLength(450)]
        public string IdUser { get; set; }
        [Required]
        [StringLength(8)]
        [Unicode(false)]
        public string VehiclePlate { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string EconomicNumber { get; set; }
        [Column("ID_VIATags")]
        public int IdViatags { get; set; }
        public virtual Viapasstags IdViatagsNavigation { get; set; }
    }
}