// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Table("Tariff")]
    public partial class Tariff
    {
        public Tariff()
        {
            Transactions = new HashSet<Transaction>();
        }

        [Key]
        [Column("ID_Tariff")]
        public int IdTariff { get; set; }
        [Column("ID_TariffVersion")]
        public int IdTariffVersion { get; set; }
        [Column("ID_Class")]
        public int IdClass { get; set; }
        [Column("ID_Catalog")]
        public int IdCatalog { get; set; }
        [Column("Tariff", TypeName = "decimal(18, 0)")]
        public decimal Tariff1 { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Vat { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal TotalTariff { get; set; }

        [ForeignKey("IdCatalog")]
        [InverseProperty("Tariffs")]
        public virtual LaneCatalog IdCatalogNavigation { get; set; }
        [ForeignKey("IdClass")]
        [InverseProperty("Tariffs")]
        public virtual TypeClass IdClassNavigation { get; set; }
        [InverseProperty("IdTariffNavigation")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}