// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Table("TypePayment")]
    public partial class TypePayment
    {
        public TypePayment()
        {
            Transactions = new HashSet<Transaction>();
        }

        [Key]
        [Column("ID_Payment")]
        public int IdPayment { get; set; }
        [Required]
        [StringLength(100)]
        public string PaymentName { get; set; }

        [InverseProperty("IdPaymentNavigation")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}