// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Keyless]
    [Table("Type_Carril")]
    public partial class TypeCarril
    {
        [Column("Id_Carril")]
        public int IdCarril { get; set; }
        [Column("Num_Gea")]
        [StringLength(10)]
        [Unicode(false)]
        public string NumGea { get; set; }
        [Column("Num_Capufe")]
        [StringLength(10)]
        [Unicode(false)]
        public string NumCapufe { get; set; }
        [Column("Num_Tramo")]
        [StringLength(10)]
        [Unicode(false)]
        public string NumTramo { get; set; }
        [Column("Plaza_Id")]
        public int PlazaId { get; set; }
    }
}