// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Keyless]
    [Table("Type_Operadores")]
    public partial class TypeOperadores
    {
        [Column("Id_Operador")]
        public int IdOperador { get; set; }
        [Column("Num_Capufe")]
        [StringLength(20)]
        [Unicode(false)]
        public string NumCapufe { get; set; }
        [Column("Num_Gea")]
        [StringLength(20)]
        [Unicode(false)]
        public string NumGea { get; set; }
        [Column("Nom_Operador")]
        [StringLength(150)]
        [Unicode(false)]
        public string NomOperador { get; set; }
        [Column("Plaza_Id")]
        public int PlazaId { get; set; }
    }
}