// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Table("TypeClass")]
    public partial class TypeClass
    {
        public TypeClass()
        {
            Tariffs = new HashSet<Tariff>();
            TransactionIdClass2Navigation = new HashSet<Transaction>();
            TransactionIdClassNavigations = new HashSet<Transaction>();
        }

        [Key]
        [Column("ID_Class")]
        public int IdClass { get; set; }
        [Required]
        [StringLength(150)]
        public string NameClass { get; set; }
        [Required]
        [StringLength(20)]
        public string ClassCode { get; set; }

        [InverseProperty("IdClassNavigation")]
        public virtual ICollection<Tariff> Tariffs { get; set; }
        [InverseProperty("IdClass2Navigation")]
        public virtual ICollection<Transaction> TransactionIdClass2Navigation { get; set; }
        [InverseProperty("IdClassNavigation")]
        public virtual ICollection<Transaction> TransactionIdClassNavigations { get; set; }
    }
}