// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Keyless]
    [Table("Type_Plaza")]
    public partial class TypePlaza
    {
        [Column("Id_Plaza")]
        public int IdPlaza { get; set; }
        [Column("Num_Plaza")]
        [StringLength(10)]
        [Unicode(false)]
        public string NumPlaza { get; set; }
        [Column("Nom_Plaza")]
        [StringLength(100)]
        [Unicode(false)]
        public string NomPlaza { get; set; }
        [Column("Delegacion_Id")]
        public int DelegacionId { get; set; }
    }
}