// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Keyless]
    [Table("Type_Delegacion")]
    public partial class TypeDelegacion
    {
        [Column("Id_Delegacion")]
        public int IdDelegacion { get; set; }
        [Column("Num_Delegacion")]
        [StringLength(10)]
        [Unicode(false)]
        public string NumDelegacion { get; set; }
        [Column("Nom_Delegacion")]
        [StringLength(100)]
        [Unicode(false)]
        public string NomDelegacion { get; set; }
    }
}