// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models
{
    [Table("UsersOPE")]
    public partial class UsersOpe
    {
        public UsersOpe()
        {
            FinalPosts = new HashSet<FinalPost>();
            Transactions = new HashSet<Transaction>();
        }

        [Key]
        [Column("Id_UserOPE")]
        public int IdUserOpe { get; set; }
        [Column("NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("USERNAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string Username { get; set; }
        [Required]
        [Column("FunctionOPE")]
        [StringLength(50)]
        [Unicode(false)]
        public string FunctionOpe { get; set; }
        [Column("MATRICULE")]
        [StringLength(10)]
        [Unicode(false)]
        public string Matricule { get; set; }

        [InverseProperty("IdUserNavigation")]
        public virtual ICollection<FinalPost> FinalPosts { get; set; }
        [InverseProperty("IdUserNavigation")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}